Repository rudderlabs/rudder-sdk-js, pull requests merged in 2021-10, with the labels that each got.

#348 Enhancement: Added API overloads for NPM package that SDK supports
  .eslintignore
  dist/rudder-sdk-js/index.d.ts
Labels: enhancement, Ready for review

#351 NPM package v1.0.20 published
  dist/rudder-sdk-js/package.json
Labels: Ready for review

#350 Updated structure and revamped content
  README.md
  dist/rudder-sdk-js/README.md
Labels: documentation, Ready for review
