Repository rudderlabs/rudder-sdk-js, pull requests merged in 2021-12, with the labels that each got.

#385 bugfix : sriptloader async logic update
  integrations/ScriptLoader.js
Labels: Ready for review

#380 TVSquared - fix: add check for deleteCustomVariable
  integrations/TVSquared/browser.js
Labels: bug

#394 Google Ads - feat: add dynamic remarketing
  integrations/GoogleAds/browser.js
Labels: enhancement

#396 FB Pixel - feat: Handle duplicate pixel
  integrations/FacebookPixel/browser.js
Labels: enhancement, Ready for review

#388 Enhancement Klaviyo : Introducing Ecom Events for Track calls
  integrations/Klaviyo/browser.js
  integrations/Klaviyo/util.js
Labels: Ready for review

#398 add secure cookie flag
  analytics.js
Labels: enhancement, Ready for review

#400 JS SDK v1 with beacon feature
  analytics.js
  dist/rudder-sdk-js/package.json
  package.json
  utils/EventRepository.js
  utils/constants.js
  utils/storage/beaconQueue.js
  utils/xhrModule.js
Labels: Ready for review
