Repository rudderlabs/rudder-sdk-js, pull requests merged in 2022-05, with the labels that each got.

#502 Fix product id, quantity and price mapping
  integrations/FacebookPixel/browser.js
Labels: Ready for review

#504 feature(new integration): Adroll Web Device Mode
  integrations/Adroll/browser.js
  integrations/Adroll/constants.js
  integrations/Adroll/index.js
  integrations/Adroll/util.js
  integrations/client_server_name.js
  integrations/index.js
  integrations/integration_cname.js
Labels: enhancement, Ready for review

#521 Broken URLs hotfix
  README.md
Labels: documentation

#522 Align Ready method's behaviour
  analytics.js
Labels: Ready for review

#515 feature(new integration): DCM device mode integration onboarding
  integrations/DCMFloodlight/browser.js
  integrations/DCMFloodlight/constants.js
  integrations/DCMFloodlight/index.js
  integrations/DCMFloodlight/utils.js
  integrations/client_server_name.js
  integrations/index.js
  integrations/integration_cname.js
Labels: Ready for review, new-integration
