Repository rudderlabs/rudder-sdk-js, pull requests merged in 2022-10, with the labels that each got.

#672 feat(new integration): Engage - onboard integration
  .size-limit.js
  integrations/Engage/browser.js
  integrations/Engage/index.js
  utils/client_server_name.js
  utils/config_to_integration_names.js
  utils/integration_cname.js
Labels: Ready for review, new-integration

#673 feat(new integration): onboarding june device mode destination v1.1
  .size-limit.js
  integrations/June/index.js
  utils/client_server_name.js
  utils/config_to_integration_names.js
  utils/integration_cname.js
Labels: new-integration

#670 feat(new integration): Iterable - onboard integration
  integrations/Iterable/browser.js
  integrations/Iterable/constants.js
  integrations/Iterable/index.js
  integrations/Iterable/utils.js
  integrations/client_server_name.js
  integrations/index.js
  integrations/integration_cname.js
Labels: new-integration

#671 feat(new-integration): onboarding yandex.metrica destination
  integrations/YandexMetrica/browser.js
  integrations/YandexMetrica/constants.js
  integrations/YandexMetrica/index.js
  integrations/YandexMetrica/utils.js
  integrations/client_server_name.js
  integrations/index.js
  integrations/integration_cname.js
Labels: new-integration

#681 fix: common names map update
  integrations/AdobeAnalytics/constants.js
  integrations/Adroll/constants.js
  integrations/Amplitude/constants.js
  integrations/Appcues/constants.js
  integrations/BingAds/constants.js
  integrations/Braze/constants.js
  integrations/Bugsnag/constants.js
  integrations/Chartbeat/constants.js
  integrations/Clevertap/constants.js
  integrations/Comscore/constants.js
  integrations/ConvertFlow/constants.js
  integrations/CustomerIO/constants.js
  integrations/DCMFloodlight/constants.js
  integrations/Engage/constants.js
  integrations/FacebookPixel/constants.js
  integrations/Fullstory/constants.js
  integrations/GA/constants.js
  integrations/GA360/constants.js
  integrations/GA4/constants.js
  integrations/GoogleAds/constants.js
  integrations/GoogleOptimize/constants.js
  integrations/GoogleTagManager/constants.js
  integrations/Hotjar/constants.js
  integrations/HubSpot/constants.js
  integrations/INTERCOM/constants.js
  integrations/Keen/constants.js
  integrations/Kissmetrics/constants.js
  integrations/Klaviyo/constants.js
  integrations/LaunchDarkly/constants.js
  integrations/LinkedInInsightTag/constants.js
  integrations/LiveChat/constants.js
  integrations/Lotame/constants.js
  integrations/Lytics/constants.js
  integrations/Matomo/constants.js
  integrations/Mixpanel/constants.js
  integrations/MoEngage/constants.js
  integrations/Mouseflow/constants.js
  integrations/Optimizely/constants.js
  integrations/Pendo/constants.js
  integrations/PinterestTag/constants.js
  integrations/PostAffiliatePro/constants.js
  integrations/Posthog/constants.js
  integrations/ProfitWell/constants.js
  integrations/QuantumMetric/constants.js
  integrations/QuoraPixel/constants.js
  integrations/Rockerbox/constants.js
  integrations/Shynet/constants.js
  integrations/SnapEngage/constants.js
  integrations/TVSquared/constants.js
  integrations/VWO/constants.js
  integrations/Woopra/constants.js
Labels: Ready for review

#668 feat:(service-worker): new service worker compatible SDK with samples
  .gitignore
  README.md
  __tests__/service-worker/__mocks__/fixtures.js
  __tests__/service-worker/__mocks__/msw.server.js
  __tests__/service-worker/index.test.js
  dist/rudder-sdk-js/package.json
  jest.config.js
  jest/jest.polyfills.js
  package-lock.json
  package.json
  rollup.worker.config.js
  rollupUtils.js
  service-worker/index.d.ts
  service-worker/index.js
  tests/chrome-extension/USAGE.md
  tests/chrome-extension/background-script/LICENSE
  tests/chrome-extension/background-script/README.md
  tests/chrome-extension/background-script/foreground.js
  tests/chrome-extension/background-script/logo/logo-128.png
  tests/chrome-extension/background-script/logo/logo-16.png
  tests/chrome-extension/background-script/logo/logo-48.png
  tests/chrome-extension/background-script/logo/logo.svg
  tests/chrome-extension/background-script/manifest.json
  tests/chrome-extension/background-script/popup/popup.css
  tests/chrome-extension/background-script/popup/popup.html
  tests/chrome-extension/background-script/rudderAnalytics.js
  tests/chrome-extension/background-script/service-worker.js
  tests/chrome-extension/background-script/settings/settings.css
  tests/chrome-extension/background-script/settings/settings.html
  tests/chrome-extension/content-script/LICENSE
  tests/chrome-extension/content-script/README.md
  tests/chrome-extension/content-script/foreground.js
  tests/chrome-extension/content-script/logo/logo-128.png
  tests/chrome-extension/content-script/logo/logo-16.png
  tests/chrome-extension/content-script/logo/logo-48.png
  tests/chrome-extension/content-script/logo/logo.svg
  tests/chrome-extension/content-script/manifest.json
  tests/chrome-extension/content-script/popup/popup.css
  tests/chrome-extension/content-script/popup/popup.html
  tests/chrome-extension/content-script/service-worker-utils.js
  tests/chrome-extension/content-script/service-worker.js
  tests/chrome-extension/content-script/settings/settings.css
  tests/chrome-extension/content-script/settings/settings.html
Labels: Ready for review

#687 feat/yandex_metirca: onbaording yandex_metrica
  .size-limit.js
  integrations/YandexMetrica/index.js
  utils/client_server_name.js
  utils/config_to_integration_names.js
  utils/integration_cname.js
Labels: Ready for review

#688 feat: posthog group call support
  integrations/Posthog/browser.js
Labels: enhancement, Ready for review

#699 fix: refiner group call email conflicts issue
  integrations/Refiner/browser.js
Labels: Ready for review

#696 fix(service-worker): fix npm package exports and types
  CODEOWNERS
  README.md
  dist/rudder-sdk-js/package.json
  service-worker/index.d.ts
  tests/chrome-extension/USAGE.md
Labels: Ready for review

#700 fix(service-worker): fix npm package exports and types (#696)
  CODEOWNERS
  README.md
  dist/rudder-sdk-js/package.json
  service-worker/index.d.ts
  tests/chrome-extension/USAGE.md
Labels: Ready for review

#705 fix: refiner device mode code removed
  integrations/Refiner/browser.js
  integrations/Refiner/constants.js
  integrations/Refiner/index.js
  integrations/Refiner/utils.js
  integrations/client_server_name.js
  integrations/index.js
  integrations/integration_cname.js
Labels: Ready for review

#711 fix: remove non tree shaked code of utils from service worker bundle
  package-lock.json
  package.json
  service-worker/index.js
  tests/chrome-extension/background-script/rudderAnalytics.js
Labels: Ready for review

#710 feat: refiner device mode integration
  integrations/Refiner/browser.js
  integrations/Refiner/constants.js
  integrations/Refiner/index.js
  integrations/Refiner/utils.js
  integrations/client_server_name.js
  integrations/index.js
  integrations/integration_cname.js
Labels: Ready for review

#713 feat: refiner device mode integration
  .size-limit.js
  integrations/Refiner/index.js
  utils/client_server_name.js
  utils/config_to_integration_names.js
  utils/integration_cname.js
Labels: Ready for review

#680 fix(core): execute buffered requests during load API
  analytics.js
Labels: Ready for review
