Repository rudderlabs/rudder-sdk-js, pull requests merged in 2022-08, with the labels that each got.

#592 Launchdarkly Fix
  integrations/LaunchDarkly/browser.js
Labels: Ready for review

#590 feature/mouseflow: new Integration Onboarding
  integrations/Mouseflow/browser.js
  integrations/Mouseflow/constants.js
  integrations/Mouseflow/index.js
  integrations/Mouseflow/utils.js
  integrations/client_server_name.js
  integrations/index.js
  integrations/integration_cname.js
Labels: Ready for review, new-integration

#595 feature(event filtering): criteo onetag
  integrations/Criteo/browser.js
  integrations/Criteo/constants.js
  integrations/utils/commonUtils.js
Labels: enhancement, Ready for review

#599 feature/mouseflow: Onboarding new-integrations, web device mode
  .size-limit.js
  integrations/Mouseflow/index.js
  utils/config_to_integration_names.js
  utils/integration_cname.js
Labels: Ready for review, new-integration

#594 Feature(Fb Pixel): Compatibilty with cloud mode
  integrations/FacebookPixel/browser.js
Labels: enhancement

#597 feature/new integration: RockerBox onboarding
  integrations/Rockerbox/browser.js
  integrations/Rockerbox/constants.js
  integrations/Rockerbox/index.js
  integrations/client_server_name.js
  integrations/index.js
  integrations/integration_cname.js
Labels: new-integration

#609 feature/new integration: Onboarding rockerbox for v1.1
  integrations/Rockerbox/index.js
  utils/client_server_name.js
  utils/config_to_integration_names.js
  utils/integration_cname.js
Labels: Ready for review, new-integration

#611 feature/new integration: Convertflow onboarding
  integrations/ConvertFlow/browser.js
  integrations/ConvertFlow/constants.js
  integrations/ConvertFlow/index.js
  integrations/ConvertFlow/utils.js
  integrations/client_server_name.js
  integrations/index.js
  integrations/integration_cname.js
Labels: new-integration

#612 feature(new integration): SnapEngage web Device mode integration onboarding
  integrations/SnapEngage/browser.js
  integrations/SnapEngage/constants.js
  integrations/SnapEngage/index.js
  integrations/SnapEngage/util.js
  integrations/client_server_name.js
  integrations/index.js
  integrations/integration_cname.js
Labels: new-integration

#616 bugfix(ConvertFlow): correcting typo in event name
  integrations/ConvertFlow/utils.js
Labels: bug fix

#619 feature(ConvertFlow): Onboarding COnvertFlow for v1.1
  .size-limit.js
  integrations/ConvertFlow/index.js
  utils/client_server_name.js
  utils/config_to_integration_names.js
  utils/integration_cname.js
Labels: Ready for review

#625 Type declaration updated
  dist/rudder-sdk-js/index.d.ts
Labels: Ready for review

#626 fix(snappixel): cookie check
  integrations/SnapPixel/browser.js
Labels: bug fix
