Repository rudderlabs/rudder-sdk-js, pull requests merged in 2022-09, with the labels that each got.

#629 Feature(Intercom): Adding support of flattenJson in track call properties.
  integrations/INTERCOM/browser.js
  utils/utils.js
Labels: enhancement

#636 feat (rockerbox): add anonymousId for all calls
  integrations/Rockerbox/browser.js
Labels: enhancement, new-integration

#635 Enhancement(Integration): Pinterest Tag event_id added for deduplication + custom event support
  integrations/PinterestTag/browser.js
Labels: enhancement

#617 Upgrade/braze web sdk
  integrations/Braze/browser.js
  integrations/Braze/constants.js
Labels: working on it, integration-upgrade

#649 feat(quora pixel): add data-loader attribute
  integrations/QuoraPixel/browser.js
Labels: Ready for review

#645 feature(new integration): Woopra Device Mode Onboarding
  integrations/Woopra/browser.js
  integrations/Woopra/constants.js
  integrations/Woopra/index.js
  integrations/client_server_name.js
  integrations/index.js
  integrations/integration_cname.js
Labels: Ready for review, new-integration

#648 feat(LinkedIn Insights Tag): add support for event-specific conversion
  integrations/LinkedInInsightTag/browser.js
Labels: enhancement

#643 feat(integration): add common util function for mapping event names in ads destinations
  integrations/GoogleAds/browser.js
  integrations/RedditPixel/browser.js
  integrations/SnapPixel/browser.js
  integrations/utils/commonUtils.js
Labels: enhancement

#653 feature(new integration): quora pixel destination onboarding v1.1
  .size-limit.js
  integrations/QuoraPixel/index.js
  utils/client_server_name.js
  utils/config_to_integration_names.js
  utils/integration_cname.js
Labels: Ready for review

#651 feature(new integration): Onboarding Woopra Destination
  integrations/Woopra/index.js
  utils/client_server_name.js
  utils/config_to_integration_names.js
  utils/integration_cname.js
Labels: Ready for review, new-integration

#637 feat (core): user session
  analytics.js
  dist/rudder-sdk-js/index.d.ts
  session/index.js
  utils/constants.js
  utils/storage/storage.js
  utils/utils.js
Labels: DO NOT MERGE, beta testing in progress

#656 fix(integration): error message in LinkedIn Insight Tag
  integrations/LinkedInInsightTag/browser.js
Labels: bug fix

#613 Fix: Permission denied accessing error message
  analytics.js
  utils/utils.js
Labels: Ready for review

#663 feat(new integration): onboarding june device mode destination
  integrations/June/browser.js
  integrations/June/constants.js
  integrations/June/index.js
  integrations/client_server_name.js
  integrations/index.js
  integrations/integration_cname.js
  integrations/utils/commonUtils.js
Labels: new-integration

#659 feat(integration): add multiplexing support to Pinterest Tag
  integrations/PinterestTag/browser.js
Labels: Ready for review, integration-upgrade

#662 feat(new integration): Onboarding Engage Device Mode
  integrations/Engage/browser.js
  integrations/Engage/constants.js
  integrations/Engage/index.js
  integrations/Engage/utils.js
  integrations/client_server_name.js
  integrations/index.js
  integrations/integration_cname.js
  utils/utils.js
Labels: Ready for review, new-integration
