Repository rudderlabs/rudder-sdk-js, pull requests merged in 2022-12, with the labels that each got.

#745 fix(core): replicate lodash merge behaviour with ramda
  __tests__/utils/ObjectUtils.test.js
  src/core/analytics.js
  src/utils/ObjectUtils.js
Labels: Ready for review

#743 feat/axeptio: onboard web device mode destination axeptio
  integrations/Axeptio/browser.js
  integrations/Axeptio/constants.js
  integrations/Axeptio/index.js
  integrations/Axeptio/utils.js
  integrations/client_server_name.js
  integrations/index.js
  integrations/integration_cname.js
Labels: new-integration

#754 ci: added build and deploy github actions for staging and prod v1
  .github/workflows/deploy-prod-v1.yml
  .github/workflows/deploy-staging-v1.yml
Labels: Ready for review

#749 feat: onboard microsoft clarity destination
  .size-limit.js
  src/integrations/MicrosoftClarity/browser.js
  src/integrations/MicrosoftClarity/constants.js
  src/integrations/MicrosoftClarity/index.js
  src/integrations/index.js
  src/utils/client_server_name.js
  src/utils/config_to_integration_names.js
  src/utils/integration_cname.js
Labels: Ready for review, new-integration

#761 fix: braze update supportDedup
  src/integrations/Braze/browser.js
Labels: bug fix

#752 feat: onbaord destination axeptio
  .size-limit.js
  src/integrations/Axeptio/browser.js
  src/integrations/Axeptio/constants.js
  src/integrations/Axeptio/index.js
  src/integrations/Axeptio/utils.js
  src/integrations/index.js
  src/utils/client_server_name.js
  src/utils/config_to_integration_names.js
  src/utils/integration_cname.js
Labels: Ready for review, new-integration

#760 ci: fix v1 deployment actions
  .github/workflows/deploy-prod-v1.yml
  .github/workflows/deploy-staging-v1.yml
  .github/workflows/size-limit.yml
  .github/workflows/tests.yml
  __tests__/utils/ObjectUtils.test.js
Labels: Ready for review

#747 feat: onboard ga4 hybrid mode
  src/core/analytics.js
  src/integrations/GA4/browser.js
  src/integrations/GA4/utils.js
Labels: Ready for review

#769 feat: getSessionId API
  packages/npm/index.d.ts
  src/core/analytics.js
  src/features/core/session/index.js
Labels: Ready for review

#787 fix(core): error mutation coming from integration
  __tests__/utils/errorHandler.test.js
  package-lock.json
  src/core/analytics.js
  src/features/core/session/index.js
  src/utils/beaconQueue.js
  src/utils/errorHandler.js
  src/utils/utils.js
  src/utils/xhrModule.js
Labels: Ready for review

#785 feat(new integration): onboarding sendinblue web device mode destination
  src/integrations/Sendinblue/browser.js
  src/integrations/Sendinblue/constants.js
  src/integrations/Sendinblue/index.js
  src/integrations/Sendinblue/utils.js
  src/integrations/client_server_name.js
  src/integrations/index.js
  src/integrations/integration_cname.js
  src/integrations/utils/commonUtils.js
Labels: Ready for review, new-integration

#801 ci: tag releases on producton branch instead of release, fix slack msg
  .github/workflows/deploy-npm.yml
  .github/workflows/draft-new-release-v1.yml
  .github/workflows/draft-new-release.yml
  .github/workflows/publish-new-release-v1.yml
  .github/workflows/publish-new-release.yml
Labels: Ready for review

#802 ci: tag releases on producton branch instead of release, fix slack msg
  .github/workflows/draft-new-release-v1.yml
  .github/workflows/publish-new-release-v1.yml
Labels: Ready for review

#805 feat: ga4 hybrid mode support
  src/core/analytics.js
  src/integrations/GA4/browser.js
  src/integrations/GA4/utils.js
Labels: enhancement, Ready for review

#808 feat: ga4 hybrid mode
  __tests__/utils/integrationsData.test.js
  package-lock.json
  package.json
  src/core/analytics.js
  src/utils/IntegrationsData.js
  src/utils/ObjectUtils.js
Labels: Ready for review

#762 feat: onboard olark web device mode
  src/integrations/Olark/browser.js
  src/integrations/Olark/constants.js
  src/integrations/Olark/index.js
  src/integrations/Olark/utils.js
  src/integrations/client_server_name.js
  src/integrations/index.js
  src/integrations/integration_cname.js
Labels: Ready for review, new-integration

#813 feat: add option to allow version locking of js integrations
  .github/workflows/deploy-prod.yml
  .github/workflows/deploy-staging.yml
  .size-limit.js
  __tests__/utils/cdnPaths.test.js
  package-lock.json
  package.json
  packages/npm/index.d.ts
  src/core/analytics.js
  src/utils/RudderApp.js
  src/utils/cdnPaths.js
  src/utils/constants.js
Labels: Ready for review
