Repository rudderlabs/rudder-sdk-js, pull requests merged in 2022-07, with the labels that each got.

#550 feature(new integration): Matomo web Device mode integration onboarding
  integrations/Matomo/browser.js
  integrations/Matomo/constants.js
  integrations/Matomo/index.js
  integrations/Matomo/util.js
  integrations/client_server_name.js
  integrations/index.js
  integrations/integration_cname.js
  integrations/utils/commonUtils.js
  utils/constants.js
Labels: new-integration

#556 feature(new integration): Vero web Device mode integration onboarding-production
  integrations/Vero/index.js
  utils/config_to_integration_names.js
  utils/integration_cname.js
Labels: new-integration

#559 bugfix(vero): Vero tags object checked
  integrations/Vero/browser.js
Labels: bug fix

#561 bugfix(non CFD): Matomo production PR
  integrations/Matomo/browser.js
  integrations/Matomo/util.js
  integrations/utils/commonUtils.js
Labels: Ready for review, bug fix

#564 Readme update
  README.md
Labels: Ready for review

#571 bugfix[SnapPixel]: update init, identify and track call
  integrations/SnapPixel/browser.js
  integrations/SnapPixel/util.js
Labels: Ready for review, bug fix

#565 feature/ga4 debug mode support
  integrations/GA4/browser.js
Labels: enhancement

#575 Support LaunchDarkly anonymous users shared key
  integrations/LaunchDarkly/browser.js
  integrations/LaunchDarkly/utils.js
Labels: Ready for review, bug fix
