Repository rudderlabs/rudder-sdk-js, pull requests merged in 2022-11, with the labels that each got.

#717 enhancement [integration] :: pinterest tag user defined event support
  integrations/PinterestTag/browser.js
Labels: enhancement

#715 feat(new integration): onboarding qualaroo device mode destination
  integrations/Qualaroo/browser.js
  integrations/Qualaroo/constants.js
  integrations/Qualaroo/index.js
  integrations/Qualaroo/utils.js
  integrations/client_server_name.js
  integrations/index.js
  integrations/integration_cname.js
Labels: Ready for review, new-integration

#709 feat(Podsights): Onboarding new destination
  integrations/Podsights/browser.js
  integrations/Podsights/constants.js
  integrations/Podsights/index.js
  integrations/Podsights/utils.js
  integrations/client_server_name.js
  integrations/index.js
  integrations/integration_cname.js
Labels: Ready for review, new-integration

#720 feat(new integration): onboarding qualaroo device mode destination
  integrations/Qualaroo/index.js
  utils/client_server_name.js
  utils/config_to_integration_names.js
  utils/integration_cname.js
Labels: Ready for review, new-integration

#721 feat(Podsights): Onboarding new destination
  .size-limit.js
  integrations/Podsights/index.js
  utils/client_server_name.js
  utils/config_to_integration_names.js
  utils/integration_cname.js
Labels: Ready for review, new-integration

#736 chore: add SECURITY.md
  SECURITY.md
Labels: documentation

#723 feature: posthog option to not load core sdk
  integrations/Posthog/browser.js
Labels: Ready for review

#732 feat(destination): onboard satismeter
  integrations/Satismeter/browser.js
  integrations/Satismeter/constants.js
  integrations/Satismeter/index.js
  integrations/Satismeter/util.js
  integrations/client_server_name.js
  integrations/index.js
  integrations/integration_cname.js
Labels: Ready for review, new-integration

#728 feat(destination): add dedup support for identify call in Braze
  integrations/Braze/browser.js
  package.json
Labels: enhancement, Ready for review

#744 build: configured modern builds to generate target output as es2015
  package-lock.json
  package.json
  rollup-configs/rollup.integrations.config.js
  rollup-configs/rollup.sdk.browser.js
Labels: Ready for review

#731 feat: ga4 hybrid mode support
  integrations/GA4/browser.js
  integrations/GA4/utils.js
Labels: Ready for review

#719 fix(destination): custom properties support in ga4
  integrations/GA4/ECommerceEventConfig.js
  integrations/GA4/browser.js
  integrations/GA4/utils.js
  package.json
Labels: enhancement
