Repository rudderlabs/rudder-sdk-js, pull requests merged in 2023-09, with the labels that each got.

#1366 feat(INT-580): messageId to event_id mapping support
  .size-limit.js
  __tests__/integrations/TikTokAds/tiktokads.test.js
  src/integrations/TiktokAds/constants.js
Labels: enhancement, Ready for review

#1365 fix(INT-580): object.formEntries is not a function
  src/integrations/GA4/utils.js
Labels: Ready for review, bug fix

#1367 fix(INT-523): replaced flag with dropdown for datacenter selection
  src/integrations/CustomerIO/browser.js
  src/integrations/CustomerIO/nativeSdkLoader.js
Labels: Ready for review

#1376 feat(INT-645): added proxyUrl support
  .size-limit.js
  src/integrations/Appcues/browser.js
Labels: Ready for review

#1413 feat(Amplitude): update amplitude SDK
  packages/analytics-js-integrations/src/integrations/Amplitude/browser.js
  packages/analytics-js-integrations/src/integrations/Amplitude/nativeSdkLoader.js
Labels: draft

#1417 feat(analytics-js-integrations): ga4 enhancements
  packages/analytics-js-integrations/__tests__/integrations/GA4/__mocks__/data.js
  packages/analytics-js-integrations/__tests__/integrations/GA4/browser.test.js
  packages/analytics-js-integrations/__tests__/integrations/GA4/utils.test.js
  packages/analytics-js-integrations/src/integrations/GA4/browser.js
  packages/analytics-js-integrations/src/integrations/GA4/utils.js
Labels: Ready for review

#1419 fix(ga4): remove sendUserTraitsAsPartOfInIt field
  packages/analytics-js-integrations/__tests__/integrations/GA4/browser.test.js
  packages/analytics-js-integrations/__tests__/integrations/GA4/utils.test.js
  packages/analytics-js-integrations/src/integrations/GA4/browser.js
  packages/analytics-js-integrations/src/integrations/GA4/utils.js
Labels: Ready for review
