Repository rudderlabs/rudder-sdk-js, pull requests merged in 2023-01, with the labels that each got.

#810 feat(pinterest): add ldp support
  src/integrations/PinterestTag/browser.js
  src/utils/utils.js
Labels: enhancement, Ready for review

#812 feat(pinterest): add ldp support
  .size-limit.js
  src/integrations/PinterestTag/browser.js
  src/utils/utils.js
Labels: enhancement, Ready for review

#820 fix: detection of sessionId for GA4 if no cookie exists, add unit test
  __tests__/integrations/GA4/utils.test.js
  src/integrations/GA4/utils.js
Labels: Ready for review

#786 feat: onboard ga4 hybrid mode
  .size-limit.js
  __tests__/integrations/GA4/utils.test.js
  __tests__/utils/IntegrationsData.test.js
  src/core/analytics.js
  src/integrations/GA4/browser.js
  src/integrations/GA4/utils.js
  src/utils/IntegrationsData.js
Labels: Ready for review

#763 feat: onboard olark web device mode
  .size-limit.js
  src/integrations/Olark/browser.js
  src/integrations/Olark/constants.js
  src/integrations/Olark/index.js
  src/integrations/Olark/utils.js
  src/integrations/index.js
  src/utils/client_server_name.js
  src/utils/config_to_integration_names.js
  src/utils/integration_cname.js
Labels: Ready for review, new-integration

#804 feat(new integration): onboarding sendinblue web device mode destination
  .size-limit.js
  src/integrations/Sendinblue/browser.js
  src/integrations/Sendinblue/constants.js
  src/integrations/Sendinblue/index.js
  src/integrations/Sendinblue/utils.js
  src/integrations/index.js
  src/utils/client_server_name.js
  src/utils/commonUtils.js
  src/utils/config_to_integration_names.js
  src/utils/integration_cname.js
Labels: Ready for review, new-integration

#790 fix(destination): facebook pixel userData capturing fix for both identified and annonymous users
  __tests__/integrations/FacebookPixel.test.js
  src/core/analytics.js
  src/integrations/FacebookPixel/browser.js
  src/integrations/FacebookPixel/constants.js
Labels: enhancement

#788 fix(destination): facebook pixel userData capturing fix for both identified and anonymous users
  __tests__/integrations/FacebookPixel.test.js
  src/integrations/FacebookPixel/browser.js
  src/integrations/FacebookPixel/constants.js
  src/integrations/FacebookPixel/index.js
Labels: enhancement

#827 feat: clientId support in ga4 hybrid mode
  __tests__/integrations/GA4/utils.test.js
  __tests__/utils/integrationsData.test.js
  src/integrations/GA4/browser.js
  src/integrations/GA4/utils.js
Labels: enhancement, Ready for review

#826 feat: clientId support in ga4 hybrid mode
  __tests__/integrations/GA4/utils.test.js
  __tests__/utils/IntegrationsData.test.js
  src/integrations/GA4/browser.js
  src/integrations/GA4/utils.js
Labels: enhancement, Ready for review

#829 fix: ga4 cookie issue
  __tests__/integrations/GA4/utils.test.js
  src/integrations/GA4/browser.js
  src/integrations/GA4/utils.js
  src/utils/IntegrationsData.js
Labels: Ready for review

#831 fix(launchDarkly): ldClient Initialization
  __tests__/integrations/LaunchDarkly/__mocks__/data.js
  __tests__/integrations/LaunchDarkly/browser.test.js
  __tests__/integrations/LaunchDarkly/utils.test.js
  src/integrations/LaunchDarkly/browser.js
Labels: Ready for review, bug fix
