Repository rudderlabs/rudder-sdk-js, pull requests merged in 2023-04, with the labels that each got.

#978 fix(ga4 and ua): cookie conflicts
  src/integrations/GA4/browser.js
Labels: Ready for review

#979 fix(ua and ga4): cookie conflicts
  src/integrations/GA4/browser.js
Labels: Ready for review

#856 fix: bugsnag error reporting
  .github/workflows/deploy-dev.yml
  .github/workflows/deploy-prod.yml
  .github/workflows/deploy-staging.yml
  .size-limit.js
  __tests__/features/core/metrics/errorReporting/ErrorReportingService.test.js
  examples/SampleEventsTest.Html
  jest.config.js
  package-lock.json
  package.json
  rollup-configs/rollup.utilities.js
  src/core/analytics.js
  src/features/core/metrics/error-report/Bugsnag.js
  src/features/core/metrics/errorReporting/ErrorReportingService.js
  src/features/core/metrics/errorReporting/providers/Bugsnag.js
  src/utils/RudderApp.js
  src/utils/RudderInfo.js
  src/utils/ScriptLoader.js
  src/utils/constants.js
  src/utils/errorHandler.js
Labels: DO NOT MERGE, wip

#993 fix(GA4): add send_to parameter support by default
  src/integrations/GA4/browser.js
Labels: Ready for review

#994 fix(GA4): add send_to parameter support by default
  src/integrations/GA4/browser.js
Labels: Ready for review

#1002 feat: bingads Upgraded to latest
  src/integrations/BingAds/browser.js
Labels: Ready for review

#1003 feat: bingads Upgraded to latest
  src/integrations/BingAds/browser.js
Labels: Ready for review

#1005 fix(fb_pixel): add value in mapped event
  __tests__/integrations/FacebookPixel/FacebookPixel.test.js
  src/integrations/FacebookPixel/browser.js
Labels: bug fix

#1004 fix(fb_pixel): add value in mapped event
  __tests__/integrations/FacebookPixel/FacebookPixel.test.js
  src/integrations/FacebookPixel/browser.js
Labels: bug fix

#988 feat(GA4): override sessionId with rudder sessionId
  src/integrations/GA4/browser.js
Labels: Ready for review

#1011 chore: added bing ads test cases
  __tests__/integrations/BingAds/BingAds.test.js
  __tests__/integrations/Lemnisk/Lemnisk.test.js
Labels: Ready for review

#1012 chore: added bing ads test cases
  __tests__/integrations/BingAds/BingAds.test.js
  __tests__/integrations/Lemnisk/lemnisk.test.js
Labels: Ready for review

#1027 feat(pinterest): custom event
  __tests__/integrations/PinterestTag/__mocks__/data.js
  __tests__/integrations/PinterestTag/utils.test.js
  src/integrations/PinterestTag/browser.js
  src/integrations/PinterestTag/utils.js
Labels: enhancement

#1026 feat(pinterest): custom event
  __tests__/integrations/PinterestTag/__mocks__/data.js
  __tests__/integrations/PinterestTag/utils.test.js
  src/integrations/PinterestTag/browser.js
  src/integrations/PinterestTag/utils.js
Labels: enhancement

#1029 fix(ga4): updated hybridmode condition check
  src/integrations/GA4/browser.js
Labels: Ready for review

#1030 fix(ga4): updated hybridmode condition check
  src/integrations/GA4/browser.js
Labels: Ready for review
