Repository rudderlabs/rudder-sdk-js, pull requests merged in 2023-02, with the labels that each got.

#855 feat: added support for both click event and dynamic remarketing events
  __tests__/integrations/GoogleAds/__mocks__/data.js
  __tests__/integrations/GoogleAds/browser.test.js
  __tests__/integrations/GoogleAds/utils.test.js
  src/integrations/GoogleAds/browser.js
  src/integrations/GoogleAds/utils.js
Labels: Ready for review

#878 feat: option to opt out from loading polyfill
  packages/npm/index.d.ts
  src/core/analytics.js
Labels: Ready for review

#879 feat: option to opt out from loading polyfill
  src/core/analytics.js
Labels: Ready for review

#854 feat: added support for both click event and dynamic remarketing events
  .size-limit.js
  __tests__/integrations/GoogleAds/__mocks__/data.js
  __tests__/integrations/GoogleAds/browser.test.js
  __tests__/integrations/GoogleAds/utils.test.js
  src/integrations/GoogleAds/browser.js
  src/integrations/GoogleAds/index.js
  src/integrations/GoogleAds/utils.js
Labels: Ready for review

#857 feat(destination): onboarding new destination lemnisk
  __tests__/integrations/Lemnisk/Lemnisk.test.js
  src/integrations/Lemnisk/browser.js
  src/integrations/Lemnisk/constants.js
  src/integrations/Lemnisk/index.js
  src/integrations/client_server_name.js
  src/integrations/index.js
  src/integrations/integration_cname.js
Labels: Ready for review, new-integration

#864 feat(destination): onboard lemnisk integration
  .size-limit.js
  __tests__/integrations/Lemnisk/lemnisk.test.js
  src/integrations/Lemnisk/browser.js
  src/integrations/Lemnisk/constants.js
  src/integrations/Lemnisk/index.js
  src/integrations/index.js
  src/utils/client_server_name.js
  src/utils/config_to_integration_names.js
  src/utils/integration_cname.js
Labels: Ready for review

#718 feat: data residency
  __tests__/data-residency.test.js
  __tests__/script.test.js
  packages/npm/index.d.ts
  src/core/analytics.js
  src/utils/constants.js
  src/utils/utils.js
Labels: DO NOT MERGE

#892 fix: production staging security check issue
  package-lock.json
  package.json
Labels: Ready for review

#894 fix: v1 staging security check issue
  package-lock.json
  package.json
Labels: Ready for review

#895 fix: reverted got package
  package-lock.json
  package.json
Labels: Ready for review

#888 fix: googleads config order
  __tests__/integrations/GoogleAds/utils.test.js
  src/integrations/GoogleAds/browser.js
  src/integrations/GoogleAds/utils.js
Labels: Ready for review

#889 fix: googleads config order
  __tests__/integrations/GoogleAds/utils.test.js
  src/integrations/GoogleAds/browser.js
  src/integrations/GoogleAds/utils.js
Labels: Ready for review

#890 fix: added logic to capture full url for ga4 page_location param
  src/integrations/GA4/PageEventConfig.js
Labels: Ready for review

#891 fix: added logic to capture full url for ga4 page_location param
  src/integrations/GA4/PageEventConfig.js
Labels: Ready for review

#906 feat(ga4): add sent_to parameter in gtag event call
  src/integrations/GA4/browser.js
Labels: enhancement

#907 feat(ga4): add sent_to parameter in gtag event call
  src/integrations/GA4/browser.js
Labels: enhancement
