Repository rudderlabs/rudder-sdk-js, pull requests merged in 2024-01, with the labels that each got.

#1576 fix: bugsnag alert for google ads
  packages/analytics-js-integrations/jest.config.mjs
  packages/analytics-js-integrations/src/integrations/GoogleAds/browser.js
  packages/analytics-js-integrations/src/integrations/GoogleAds/browser.test.js
Labels: bug fix

#1570 fix(googleads): added validation to discard event if event name is no event name is present
  packages/analytics-js-integrations/__tests__/integrations/GoogleAds/__fixtures__/data.js
  packages/analytics-js-integrations/__tests__/integrations/GoogleAds/browser.test.js
  packages/analytics-js-integrations/src/integrations/GoogleAds/browser.js
  packages/analytics-js-integrations/src/integrations/GoogleAds/utils.js
Labels: Ready for review

#1579 fix: ga4 page call mappings
  packages/analytics-js-integrations/__tests__/integrations/GA4/__mocks__/data.js
  packages/analytics-js-integrations/__tests__/integrations/GA4/browser.test.js
  packages/analytics-js-integrations/src/integrations/GA4/config.js
Labels: Ready for review

#1590 feat: adding proxy server url for amplitude
  packages/analytics-js-integrations/__tests__/integrations/Amplitude/browser.test.js
  packages/analytics-js-integrations/__tests__/integrations/Amplitude/util.test.js
  packages/analytics-js-integrations/src/integrations/Amplitude/browser.js
  packages/analytics-js-integrations/src/integrations/Amplitude/utils.js
Labels: enhancement
