Repository rudderlabs/rudder-sdk-js, pull requests merged in 2024-05, with the labels that each got.

#1680 feat(criteo): add support of sha256 hashing method for email
  packages/analytics-js-integrations/__tests__/integrations/Criteo/utils.test.js
  packages/analytics-js-integrations/src/integrations/Criteo/utils.js
Labels: Ready for review

#1706 chore: readme updates
  README.md
Labels: documentation

#1709 feat: gtm messageId support for track and page
  packages/analytics-js-integrations/__tests__/integrations/GoogleTagManager/browser.test.js
  packages/analytics-js-integrations/src/integrations/GoogleTagManager/browser.js
Labels: enhancement
